spring:
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI:http://localhost:8082}
          predicates:
            - Path=${SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0:/ecomm/**}
        - id: ecomm-service
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI:http://localhost:8081}
          predicates:
            - Path=${SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0:/**}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "${SPRING_CLOUD_GATEWAY_GLOBALCORS_CORS_CONFIGURATIONS___ALLOWEDORIGINS_0}"
              - "${SPRING_CLOUD_GATEWAY_GLOBALCORS_CORS_CONFIGURATIONS___ALLOWEDORIGINS_1}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
server:
  port: ${SERVER_PORT:8080}